version: '3.8'

services:
  index-tts:
    build: .
    image: index-tts-server
    env_file:
      - .env.example
    container_name: index-tts-server
    ports:
      - "${PORT:-7861}:${PORT:-7861}"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['2']
            capabilities: [gpu]
    volumes:
    #   - ./audio_prompts:/app/audio_prompts
      - ./assets:/app/assets
      - ./output:/app/output   # 输出结果挂载
      # 挂载单个文件
      # - ./api_server_v2.py:/app/api_server_v2.py
      - ./api_server.py:/app/api_server.py
      - ./entrypoint.sh:/app/entrypoint.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-7861}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      tts_net:
        ipv4_address: 172.50.0.10

networks:
  tts_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/16