version: '3.9'

services:
  indextts2:
    container_name: indextts2-vllm
    image: indextts2-vllm-gpu
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "7861:7861"         # Web UI 端口
    volumes:
      - ./output:/app/output   # 输出结果挂载
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['2']
            capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: ["/app/entrypoint.sh"]
    networks:
      tts_net:
        ipv4_address: 172.50.0.10

networks:
  tts_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/16